### ISSUE TITLE
Brew installation failed with errors

### ISSUE THREAD

**Issue by glenthomas** [stelligent/config-lint#227]
Hello 👋 

I tried to install config-lint via brew on M1 MacBook and it failed.

I ran commands:

```
brew tap stelligent/tap
brew install config-lint
```

I received errors:

```
Error: Invalid formula: /opt/homebrew/Library/Taps/stelligent/homebrew-tap/Formula/mu-cli.rb
mu-cli: wrong number of arguments (given 1, expected 0)
Error: Invalid formula: /opt/homebrew/Library/Taps/stelligent/homebrew-tap/Formula/config-lint.rb
config-lint: wrong number of arguments (given 1, expected 0)
Error: Cannot tap stelligent/tap: invalid syntax in tap!
Warning: No available formula with the name "config-lint". Did you mean configen?
==> Searching for similarly named formulae...
This similarly named formula was found:
configen
To install it, run:
  brew install configen
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by gucis3** [comment]
2022-Aug-09: I have the very same problem, on my Mac laptop:

```
brew tap stelligent/tap  --verbose --debug
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version

==> Tapping stelligent/tap
git clone https://github.com/stelligent/homebrew-tap /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap --origin=origin --template=
Cloning into '/usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap'...
remote: Enumerating objects: 1386, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 1386 (delta 31), reused 55 (delta 26), pack-reused 1308
Receiving objects: 100% (1386/1386), 184.93 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (423/423), done.

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap/Formula/mu-cli.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap/Formula/mu-cli.rb
mu-cli: wrong number of arguments (given 1, expected 0)

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap/Formula/config-lint.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap/Formula/config-lint.rb
config-lint: wrong number of arguments (given 1, expected 0)
Error: Cannot tap stelligent/tap: invalid syntax in tap!

/usr/local/Homebrew/Library/Homebrew/tap.rb:312:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by cathal-c** [comment]
Same issue on m1 here. Unfortunately there are no released arm images either.

**Comment by goutamtadi1** [comment]
01/25/2024 on Apple chip Mac
```
14:25 $ brew install config-lint
Error: config-lint: wrong number of arguments (given 1, expected 0)
```
